language: node_js

git:
  depth: 3

branches:
  only:
    - master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"

script:
  - npm test
  - bash update-repo.sh accname master
  - bash update-repo.sh annotation-aria master
  - bash update-repo.sh aria master
  - bash update-repo.sh aria stable
  - bash update-repo.sh aria-practices master
  - bash update-repo.sh core-aam master
  - bash update-repo.sh core-aam stable
  - bash update-repo.sh css-aam master
  - bash update-repo.sh dpub-aam master
  - bash update-repo.sh dpub-aria master
  - bash update-repo.sh graphics-aam master
  - bash update-repo.sh graphics-aria master
  - bash update-repo.sh math-aam master
  - bash update-repo.sh math-aria master
  - bash update-repo.sh mathml-aam master
  - bash update-repo.sh svg-aam master

